//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionViewPopupTest.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollectionViewPopupTest.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English] CollectionView popup.
        /// </summary>
        internal static string CollectionViewPopupName {
            get {
                return ResourceManager.GetString("CollectionViewPopupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.png.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English] Item1.
        /// </summary>
        internal static string Item1 {
            get {
                return ResourceManager.GetString("Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English] Item2.
        /// </summary>
        internal static string Item2 {
            get {
                return ResourceManager.GetString("Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English] Item3.
        /// </summary>
        internal static string Item3 {
            get {
                return ResourceManager.GetString("Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English] Item4.
        /// </summary>
        internal static string Item4 {
            get {
                return ResourceManager.GetString("Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English] Item5.
        /// </summary>
        internal static string Item5 {
            get {
                return ResourceManager.GetString("Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English] Language:.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English] Select language:.
        /// </summary>
        internal static string LanguageSelectTitle {
            get {
                return ResourceManager.GetString("LanguageSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English] Show.
        /// </summary>
        internal static string ShowButton {
            get {
                return ResourceManager.GetString("ShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English] with 5 items.
        /// </summary>
        internal static string TestPopupSubtitle {
            get {
                return ResourceManager.GetString("TestPopupSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English] Test popup.
        /// </summary>
        internal static string TestPopupTitle {
            get {
                return ResourceManager.GetString("TestPopupTitle", resourceCulture);
            }
        }
    }
}
